global:
  container:
    requestsLimitsEnabled: true
  istio:
    sidecar:
      requestsLimitsEnabled: true
      resources:
        requests: {}
        limits: {}
  registry:
    userTaskManagement:
      container:
        envVars: {}
        resources:
          requests: {}
          limits: {}
      hpa:
        enabled: false
        minReplicas: 1
        maxReplicas: 3
      istio:
        sidecar:
          enabled: true
          resources:
            requests: {}
            limits: {}
      replicas: 1

podAnnotations: {}
image:
  name: user-task-management
  version: latest
port: 8080
service:
  type: ClusterIP
  port: 8080
appConfigMountPath: "/app/config"
readinessPath: "/user-task-management/actuator/health/readiness"
livenessPath: "/user-task-management/actuator/health/liveness"
redisSecretsMountPath: "/app/secrets/redis"

prometheus:
  endpoints:
    - scrapePath: "/user-task-management/actuator/prometheus"
      port: "{{ .Values.service.port }}"

# expose the service with a route or an ingress depending on platform type
ingress:
  # openshift or kubernetes
  platform: openshift

storage:
  form-data:
    type: redis
  backend:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        nodes: ${redis.endpoint}

redis:
  secretName: redis-auth


monitoring:
  namespace: openshift-monitoring

keycloak:
  realms:
    officer: officer-portal
    citizen: citizen-portal
    admin: admin
  certificatesEndpoint: /protocol/openid-connect/certs
deployProfile: prod

platform:
  security:
    csrf:
      enabled: false
